---

version: "3"

services:

  blox:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        BLOX_BUILD_HTTP_PROXY: "${http_proxy}"
        BLOX_BUILD_HTTPS_PROXY: "${https_proxy}"
        BLOX_BUILD_NO_PROXY: "${no_proxy}"
    network_mode: host
    image: "blox:local"
    volumes:
      - ${HOME}/.awsh:/home/awsh/.awsh
      - /etc/krb5.conf:/etc/krb5.conf
      - /etc/krb5.conf.d/:/etc/krb5.conf.d/
      - ${HOME}:/workspace
      - /tmp:/tmp
    environment:
      HTTP_PROXY: "${http_proxy}"
      http_proxy: "${http_proxy}"
      HTTPS_PROXY: "${https_proxy}"
      https_proxy: "${https_proxy}"
      no_proxy: "${no_proxy}"
      NO_PROXY: "${no_proxy}"
      KRB5CCNAME: "${KRB5CCNAME}"
      # DEFAULT_TERRAFORM_VERSION: "0.12.7"
